### ISSUE TITLE
Changing receiver port does not work

### ISSUE THREAD

**Issue by koshisan** [bhaptics/VRChatOSC#1]
It seems the settings is neither saved, nor used at all - I did not yet test the sender configuration, but it seems impossible to use another receiving port at this time...

**Comment by shebang79** [comment]
Changing the receiver port definitely works for me, but the setting isn't saved anywhere and if there is a config file I can edit to change the default port, I can't find it. It would be quite handy if this value was saved!

**Comment by westside** [comment]
Hi, thank you for the suggestion. 
I'll update the program soon and let you know!

**Comment by auejin** [comment]
Hello! We just released a [new update (v1.0.1)](https://github.com/bhaptics/VRChatOSC/releases/tag/v1.0.1). I think this update will get the isssue solved.
