### ISSUE TITLE
Stop motors after X seconds not working well in v1.0.2

### ISSUE THREAD

**Issue by MrDummyNL** [bhaptics/VRChatOSC#11]
Remember we have two packages for VRChat avatars.
One is v1.0.0. provided by bHaptics (via their site) and other is from 2.1.2 package from Harp.

I use 2.1.2 Harp because it works on Harp own bHapticsOSC and now tested with your v1.0.2 with added motor stop function.
When enabled, it doesn't stop. No idea why, but that is where my question comes. I know your program is using Harps code so it's not fault in Harp. It's your added timer function is not working very well.

Can work together to test the timer function more, and try solve the bug.
Also the stop button will not work if my hands are on my body, means it keep sending OSC commands.
But timer means it should stop motors even hands are on my suit colliders (sensors) in VRChat.
Because that is "if there is no change in on/off" it should simply stop motor for each touched zone.

For me, function is not working. So please take a look at it, with 2.1.2 vrchat package.
Thank you.

**Comment by auejin** [comment]
Hello! We just released a [new update (v1.1.0)](https://github.com/bhaptics/VRChatOSC/releases/tag/v1.1.0). We expect this update to resolve this issue! ;)
