### ISSUE TITLE
Port resets every startup

### ISSUE THREAD

**Issue by cadergator10** [bhaptics/VRChatOSC#18]
I need to use port 9005 since I'm using VRCOSC to route vrchat packets through to it, however every startup it defaults to port 9001.

**Comment by cadergator10** [comment]
addig to this: bhapticsosc wont receive anything from vrcosc

**Comment by auejin** [comment]
Thank you for reporting this issue! We are currently working on reproducing the bug you encountered. Could you please provide a screenshot and the log file of bHapticsOSC.exe?

**Comment by cadergator10** [comment]
> Thank you for reporting this issue! We are currently working on reproducing the bug you encountered. Could you please provide a screenshot and the log file of bHapticsOSC.exe?

I'll maybe give it another shot soon, though I'm currently on a previous version

**Comment by cadergator10** [comment]
For some reason it won't replicate the issue of the port not updating :p
