### ISSUE TITLE
Introduce Startup Parameter

### ISSUE THREAD

**Issue by koshisan** [bhaptics/VRChatOSC#2]
It seems to be impossible to start the program with OSC running as default - you always have to do a click first

**Comment by auejin** [comment]
Hello! We just released a [new update (v1.0.1)](https://github.com/bhaptics/VRChatOSC/releases/tag/v1.0.1). The new update automatically connects to VRChat receiver so that you don't have to click the button everytime you start! We hope you can give it a shot! ;)
