### ISSUE TITLE
UI not starting if vrchat receiving port is already in use

### ISSUE THREAD

**Issue by Raistrind** [bhaptics/VRChatOSC#22]
Hello,

I had the issue where OVR Toolkit was preventing the opening of the VRChatOSC app.
I suppose that OVR Toolkit is using the data receiving port from VRChat, so the VRChatOSC app would not start properly, the UI would not be shown but it'd stay active as an open program visible in the details of the task manager. 

The log would get filled with (error translated) : 
EROR bHapticsOSC.Query.OscQueryService.Start(): Error starting OSC query service: The process cannot access the file because this file is in use by another process

A solution I found was to open the bHaptics app, VRChat, close OVRToolkit and then start the VRChatOSC app, followed by OVRToolkit
In that sequence the described error would not occur

**Comment by auejin** [comment]
Hello! Thank you for providing detailed feedback regarding the issue with the program launch order. We’re happy to inform you that the latest release of [bHapticsOSC.exe (v2.1.1)](https://github.com/bhaptics/VRChatOSC/releases/tag/v2.1.1) has improved tolerance for the launch order, which should prevent issues like this from occurring. We hope you can give it a try and let us know if it resolves the problem. Thank you!
