### ISSUE TITLE
Credit original author

### ISSUE THREAD

**Issue by benaclejames** [bhaptics/VRChatOSC#3]
If you're going to copy the work of others, please consider crediting [them](https://github.com/HerpDerpinstine) at minimum, or even maintaining the commit history.
In its current state, the only evidence of this repo being copied from another is links to the [original repo](https://github.com/HerpDerpinstine/bHapticsOSC) in two files.

I for one would love to view the source code of any given program, instead of running some random exe.
Some random exe from a copied repo with source code removed, that is.

At minimum, I think it's fair to **link** the original repo in the README.md instead of just mentioning it. Seems intentionally left out given that you were able to link "AnimatorAsCode" just fine.

**Comment by westside** [comment]
Hi, I'm a developer from bhaptics, and I also contributed the original repo.
At the same time, we still have a good relationship with Herp, and talked about this issue and Herp already knows the current status.

Cannot say in detail in public, but there's a reason I  couldn't put the link but just mentioning the name.
By the way, bHaptics Player will work both Herp's VRChatOSC and our VRChatOSC.
